<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita3e6c2eedd1ff3f88b1456d0e63ae6b5
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita3e6c2eedd1ff3f88b1456d0e63ae6b5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita3e6c2eedd1ff3f88b1456d0e63ae6b5::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
